# teruxutil パッケージで使用する設定ファイル。
# このファイルの場所は環境変数 TXU_CONFIG_FILE で指定する。

config:
  #### teruxutil.openai モジュール の設定 #####
  api_key:
  azure_endpoint: # 本家 OpenAIでは不要
  openai_model_name: gpt-4
  openai_audio_transcript_model_name: whisper-1  # ← OpenAI用
  #openai_audio_transcript_model_name: whisper # ← Azure用
  openai_vision_model_name: gpt-4-vision-preview
  openai_embedding_model_name: text-embedding-3-small
  openai_temperature: 0.6
  openai_max_tokens: 2000
  openai_api_version: 2023-12-01-preview
  openai_max_retries: 10
  openai_history_enabled: false

  #### teruxutil.langchain_util モジュール の設定 #####
  langchain_chromadb_folder: langchain_chroma
  langchain_vector_store_collection_name: langchain_collection
  langchain_vector_store_type: pgvector # pgvector or chroma
  langchain_embedding_type: openai # openai or azure
  langchain_chat_type: openai # openai or azure

  #### teruxutil.chat モジュール の設定 #####
  chat_history_max_tokens: 2000
  chat_history_firestore_collection_name: txu_chat_history

  #### teruxutil.firestore モジュール の設定 #####
  cloud_firestore_database_name: (default)
  cloud_firestore_collection_name: txu_default

  #### teruxutil.cloudsql モジュール の設定 #####
  # langchain_util モジュール の pgvector を用いた vector store にも使用されます
  cloud_sql_region: # e.g. us-central1
  cloud_sql_instance_name: # e.g. hello-cloud-sql
  cloud_sql_host: localhost
  cloud_sql_port: 9470
  cloud_sql_driver: psycopg2
  cloud_sql_database_user: postgres
  cloud_sql_database_password:
  cloud_sql_database_name: # e.g. sample_db
