# teruxutil パッケージで使用する設定ファイル。
# このファイルの場所は環境変数 TXU_CONFIG_FILE で指定する。

config:
  #### teruxutil.openai モジュール の設定 #####
  openai_api_key:
  azure_endpoint: # Azure用。本家 OpenAIでは不要
  openai_model_name: gpt-4o
  openai_embedding_model_name: text-embedding-3-small
  openai_temperature: 0.6
  openai_max_tokens: 2000
  openai_api_version: 2024-02-15-preview # Azure用
  openai_max_retries: 10
  openai_history_enabled: false

  #### GCP の設定 ####
  google_cloud_project_id: # GCPのプロジェクトID e.g. test-00000

  #### teruxutil.langchain_util モジュール の設定 #####
  # chat や embedding の設定
  langchain_embedding_type: openai # openai or azure
  langchain_chat_type: openai # openai or azure

  # vector store の設定
  langchain_chromadb_folder: langchain_vector_store # bigquery の場合データセット名
  langchain_vector_store_collection_name: langchain_collection # bigquqery の場合テーブル名
  langchain_vector_store_type: pgvector # pgvector or chroma or bigqeury

  #### teruxutil.chat モジュール の設定 #####
  chat_history_max_tokens: 2000
  chat_history_firestore_collection_name: txu_chat_history

  #### teruxutil.firestore モジュール の設定 #####
  cloud_firestore_database_name: (default)
  cloud_firestore_collection_name: txu_default

  #### teruxutil.cloudsql モジュール の設定 #####
  # langchain_util モジュール の pgvector を用いた vector store にも使用されます
  cloud_sql_region: # e.g. us-central1
  cloud_sql_instance_name: # e.g. hello-cloud-sql
  cloud_sql_host: localhost
  cloud_sql_port: 9470
  cloud_sql_driver: psycopg2
  cloud_sql_database_user: postgres
  cloud_sql_database_password:
  cloud_sql_database_name: # e.g. sample_db

  #### teruxutil.bigquery モジュールの設定 #####
  # langchain_util モジュール の bigquery_vector_search を用いた vector storeにも使用されます
  bq_region: us-central1
